---
- name: NTC Templates Parser Demo
  hosts: r2
  gather_facts: false
  # vars:
  #   ansible_python_interpreter: "{{ ansible_playbook_python }}"
  tasks:
    - name: Install Package
      ansible.builtin.pip:
        name: ntc-templates
      delegate_to: localhost

    - name: Install using command
      ansible.builtin.command: pip3 install ntc-templates
      delegate_to: localhost

    - name: List Pip
      ansible.builtin.command: pip list

    - name: check rpm
      ansible.builtin.command: rpm -ql python
      ignore_errors: true

    - name: Check ansible version
      ansible.builtin.command: ansible --version
      ignore_errors: true

    - debug: msg="{{ ansible_playbook_python }}" 

    - name: Ansible CLI Parse
      ansible.utils.cli_parse:
        command: "show ip interface brief"
        parser:
          name: ansible.netcommon.ntc_templates
        set_fact: sh_ver
      register: show_ver_parser

    - name: Print sh_ver
      ansible.builtin.debug:
        msg: 
          - "{{ sh_ver }}"